#!/bin/bash

FRONTEND_TMP='src/tmp'
FRONTEND_DOCROOT_DIR='docroot/frontend'

cd $FRONTEND_DOCROOT_DIR || exit
# Don't fill the screen with warnings, only errors.
# TODO: Make sure we don't miss important warnings.
npm --loglevel=error install

drush pm-enable dkan_js_frontend -y
drush config-set system.site page.front '/home' -y
drush config-set system.site page.403 '/home' -y
drush config-set system.site page.404 '/home' -y

drush cr

echo " ** Frontend install complete."
